// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'swapDuration': string;
  'widgetWrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
