// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'appearTransition': string;
  'wrapperClass': string;
}
export const cssExports: CssExports;
export default cssExports;
