// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'homeClass': string;
  'loginClass': string;
}
export const cssExports: CssExports;
export default cssExports;
