// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'appMainClass': string;
  'homeClass': string;
  'legalClass': string;
  'loginClass': string;
  'profileClass': string;
}
export const cssExports: CssExports;
export default cssExports;
