// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'flyoverClass': string;
  'flyoverDuration': string;
  'opacityEndDuration': string;
  'tooltipClass': string;
}
export const cssExports: CssExports;
export default cssExports;
